SOURSE = graph.c stack_engine.c calculation.c logic.c input.c
CC = GCC
FLAG =   -Wall -Wextra -Werror
BUILD = ../build/


all: $(SOURSE)
	$(CC) $(FLAG) $(SOURSE) -o $(BUILD)graph
clean:
	rm -rf $(BUILD)graph

